# Generated by Django 4.2 on 2023-06-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='color_code',
            field=models.CharField(default='', max_length=255),
        ),
    ]
