# Generated by Django 4.2 on 2023-06-24 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_enrolledcourse_class_courses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Klass',
        ),
    ]
