# Generated by Django 4.2 on 2023-07-06 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0006_alter_enrolledcourse_color_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledcourse',
            old_name='color_code',
            new_name='color',
        ),
    ]
