# Generated by Django 4.2 on 2023-07-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0007_rename_color_code_enrolledcourse_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='klass',
            old_name='year',
            new_name='semester',
        ),
        migrations.AddField(
            model_name='klass',
            name='code',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
    ]
