# Generated by Django 4.2 on 2023-07-11 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timetable', '0008_rename_year_klass_semester_klass_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='klass',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
